### ISSUE TITLE
Retrieve backtrace from Report?

### ISSUE THREAD

**Issue by jbr** [yaahc/eyre#32]
Hi and thanks for eyre! I'm not sure if this is an eyre issue or an eyre-stable issue, but is there a way to get a reference to the `backtrace::Backtrace` on a Report, similar to [anyhow::Error::backtrace](https://docs.rs/anyhow/1.0.32/anyhow/struct.Error.html#method.backtrace)?

**Comment by yaahc** [comment]
yea, this should be pretty trivial, let me go make the change in stable-eyre one sec.

**Comment by yaahc** [comment]
k, @jbr https://github.com/yaahc/stable-eyre/pull/2 should add the necessary API. I'm a little worried that the `backtrace()` fn might eventually cause conflicts with `eyre` once backtrace stabilizes but some simple tests on nightly with the backtrace feature enabled made it seem like it would work fine so hopefully this is good, if not I can do a major version bump on this crate without much issue.

**Comment by yaahc** [comment]
Alrighty, @jbr I just published `0.2.1` for stable-eyre, lmk how it works!

**Comment by jbr** [comment]
Thanks!
