### ISSUE TITLE
eyre Result is not cmp

### ISSUE THREAD

**Issue by gilescope** [yaahc/eyre#34]
I tried to assert_eq! two Results but alas that doesn't seem possible? Could Result support compare if the underlying types do?

(Love color-eyre!)

**Comment by yaahc** [comment]
we might be able to expose some sort of ptr equality? I don't know. Seems fraught.

**Comment by yaahc** [comment]
I am going to go ahead and close this issue for now since I don't see any path towards achieving the goal here.
