### ISSUE TITLE
How to use a EyreHandler without installing it

### ISSUE THREAD

**Issue by lpil** [yaahc/eyre#44]
Hello! Thanks for this library, I'm really enjoying it.

I would like to use an EyreHandler in a one-off fashion to write to a string, though I couldn't work out how to do this. Oops.

Would you be able to give me any tips?

Thanks,
Louis

**Comment by lpil** [comment]
I figured something out. Thanks!

**Comment by azriel91** [comment]
@lpil What did you figure out? I'm having trouble figuring it out.

**Comment by lpil** [comment]
Sorry, I didn't use it in the end.

**Comment by yaahc** [comment]
> @lpil What did you figure out? I'm having trouble figuring it out.

FWIW here's how I'd do this:

```rust
use eyre::EyreHandler;
use std::{error::Error, fmt};

fn to_string(error: &(dyn Error + 'static), handler: &dyn EyreHandler) -> String {
    struct Stringifier<'a> {
        error: &'a (dyn Error + 'static),
        handler: &'a dyn EyreHandler,
    }

    impl fmt::Display for Stringifier<'_> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            self.handler.debug(self.error, f)
        }
    }

    Stringifier { error, handler }.to_string()
}
```

**Comment by azriel91** [comment]
@yaahc clever! Thank you very much 🙇‍♂️
