### ISSUE TITLE
[Feature Request] Support conversion to pyo3::PyErr

### ISSUE THREAD

**Issue by TheButlah** [yaahc/eyre#45]
Since eyre aims to provide a developer friendly error reporting mechanism, it would be great to not have to lose those pretty errors when crossing a FFI boundary from Rust to Python. The excellent [PyO3](https://github.com/PyO3/pyo3) crate provides a way to convert from Rust errors to python exceptions via the `PyErr` struct. 

Because of the orphan rules, this trait can only be implemented by either PyO3 or by eyre or by a newtype that the user of the API makes. Because forcing people to make a newtype isn't in line with being developer friendly or "works out of the box", I think it makes the most sense to implement it here, gated under a feature flag like `pyo3` or something so that the non-python people don't need the extra dependency.

I haven't yet explored exactly how the contextual backtrace/diagnostic info that eyre provides would actually be displayed in python, so I thought we could discuss.

**Comment by yaahc** [comment]
I'm not opposed to adding support to `PyO3` in eyre. The only issue I potentially see is if `PyO3` ever wanted to use `eyre` internally it wouldn't be able to depend on us. We should probably check with the `PyO3` developers to make sure they agree that `eyre` is the right place to put such an implementation.

**Comment by TheButlah** [comment]
I'll file an issue now and reference this. 

I'm a bit unfamiliar with exactly how cargo resolves dependencies with different features, but in the case where PyO3 wants to use eyre internally, couldn't they just omit the `pyo3` feature?

**Comment by TheButlah** [comment]
Looks like the author of PyO3 gave the all clear

**Comment by yaahc** [comment]
> I'm a bit unfamiliar with exactly how cargo resolves dependencies with different features, but in the case where PyO3 wants to use eyre internally, couldn't they just omit the `pyo3` feature?

To my knowledge no. The features that get enabled for a crate are based on your full build graph, so if some other dependency that is being linked into the same binary as PyO3 enabled the `pyo3` feature on a semver compatible version of `eyre` it would enable the feature for the version of `eyre` that `PyO3` links against and cause a build failure.

**Comment by yaahc** [comment]
> Looks like the author of PyO3 gave the all clear

Sounds good, do you plan on writing the PR yourself?

**Comment by TheButlah** [comment]
I'm unfamiliar with the internal workings of both libraries, but sounds like a reason to learn more about eyre. I can submit a PR

**Comment by yaahc** [comment]
> I'm unfamiliar with the internal workings of both libraries, but sounds like a reason to learn more about eyre. I can submit a PR

that would be awesome, and I can definitely help with the eyre side of things ^_^

**Comment by TheButlah** [comment]
Submitted the PR
