### ISSUE TITLE
`eyre!` (the macro) is kind of a weird name

### ISSUE THREAD

**Issue by dpc** [yaahc/eyre#78]
Hi. I started using `eyre` recently, switching from `anyhow`, and while it's not a big deal, it kind of bothers me every time I write `eyre!(...)`. As a non-native speaker I don't even know what it means (even after quickly googling "define eyre"), I keep forgetting how to spell it and so on. I don't mind this being the crate name - because I usually write it less often, rust-analyzer can often just auto-add the import for me, and I I understand that there's a limited number of good crate names that are not taken. But the macro, I get no rust-analyzer help, have to type it myself and it looks weird and non-informative to anyone not-familiar with that crate.

`anyhow!` was kind of weird already, but at least the word seemed more familiar.

Also, I'd like to point out - possibly to both authors of `anyhow` and `eyre` - that having these unique weird macro names makes `anyhow = { crate ="eyre", ... }` be much less likely to "just work".

Is there any reason this macro couldn't be just named `err!(...)` or something generic and informative like this?

Anyway, I enjoy this crate a lot, so thanks a lot for working on it!

**Comment by yaahc** [comment]
> Is there any reason this macro couldn't be just named `err!(...)` or something generic and informative like this?

There isn't any reason on than personal preference. For compatibility reasons the crate already provide re-exports for that macro under both `anyhow` and `format_err`. I'm guessing the second will probably be the best choice, both of our crates support that name so either one should work well for swapping back and forth between them.

> Anyway, I enjoy this crate a lot, so thanks a lot for working on it!

Thank you! I'm glad you're enjoying it 😊

**Comment by dpc** [comment]
> For compatibility reasons the crate already provide re-exports for that macro under both `anyhow!` and `format_err!`.

Oh. I didn't know that. I was looking at https://docs.rs/eyre/latest/eyre/all.html and not seeing anything like that.

Thanks!
