### ISSUE TITLE
Wrapping Mutex's Error

### ISSUE THREAD

**Issue by enricozb** [yaahc/eyre#79]
The error returned by `Mutex::lock` can't be wrapped using `WrapErr::wrap_err`. Here's a MVE:

```rust
use eyre::{eyre, Result, WrapErr};
use std::sync::Mutex;

fn main() -> Result<()> {
    let x = Mutex::new(0);
    x.lock().wrap_err("lock")?;

    // these also fail
    // x.lock().map_err(|e| eyre!(e)).wrap_err("lock")?;
    // x.lock().map_err(|e| eyre!(Arc::new(Mutex::new(e)))).wrap_err("lock")?;

    Ok(())
}
```

The raised error of the above code is:
```
error[E0599]: the method `wrap_err` exists for enum `Result<MutexGuard<'_, {integer}>, PoisonError<MutexGuard<'_, {integer}>>>`, but its trait bounds were not satisfied
   --> src/main.rs:6:14
    |
6   |       x.lock().wrap_err("lock")?;
    |                ^^^^^^^^
    |
    = note: the following trait bounds were not satisfied:
            `PoisonError<MutexGuard<'_, {integer}>>: eyre::context::ext::StdError`
            which is required by `Result<MutexGuard<'_, {integer}>, PoisonError<MutexGuard<'_, {integer}>>>: WrapErr<MutexGuard<'_, {integer}>, PoisonError<MutexGuard<'_, {integer}>>>`
            `PoisonError<MutexGuard<'_, {integer}>>: Send`
            which is required by `Result<MutexGuard<'_, {integer}>, PoisonError<MutexGuard<'_, {integer}>>>: WrapErr<MutexGuard<'_, {integer}>, PoisonError<MutexGuard<'_, {integer}>>>`

warning: unused import: `WrapErr`
 --> src/main.rs:1:26
  |
1 | use eyre::{eyre, Result, WrapErr};
  |                          ^^^^^^^
```

Is there any recommended way to get around this?

**Comment by yaahc** [comment]
I don't think so :s, the diagnostic isn't really making this clear but in almost positive the true issue is that the PoisonError from Mutex is not 'static. it contains a reference to the original mutex that was being locked that can't be allowed to outlive the original mutex, but eyre::Report can only store static errors that don't contain references for numerous reasons. It's probably possible to write an equivalent type that could handle this case but it would be incompatible with the current Report type and would be much less convenient to use.

**Comment by enricozb** [comment]
Just to check, when you say "construct a new eyre Report with a custom error message", you mean something like this:
```
x.lock().map_err(|e| eyre!("lock: {:?}", e))
```
right?

**Comment by yaahc** [comment]
It looks like printing it as debug as you showed would just output "lock: PoisonError", and the display output is not much better.

- https://doc.rust-lang.org/stable/src/std/sync/poison.rs.html#129-140

I'd probably use a custom error message since the default output from the poisoned lock isn't particularly useful.

```rust
x.lock().map_err(|_| eyre!("x lock is poisoned and cannot be locked"))
```

**Comment by enricozb** [comment]
Yeah absolutely, I just wasn't sure if I was missing some associated function of `Report` or if you suggested I use `eyre`. Thanks for the help! It sounds like it's not really feasible to support these non-`'static` errors, so I'll close this issue. Thanks again!
